### ISSUE TITLE
[shaped-scripts] Unhelpful error when dropping token with no npc_hp attribute

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-api-scripts#51]
https://app.roll20.net/forum/post/3052131/script-5e-shaped-support-script#post-3205891

TypeError: Cannot read property 'results' of undefined
    at apiscript.js:2540:59
    at checkFinishedOps (eval at <anonymous> (/home/node/d20-api-server/api.js:109:36), <anonymous>:758:7)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:109:36), <anonymous>:838:8)
    at null._onTimeout (/home/node/d20-api-server/node_modules/underscore/underscore.js:768:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by symposion** [comment]
Sadly this is a roll20 bug. I've stopped it breaking so badly but we need Roll20 to fix the underlying problem to get HP rolling working again

**Comment by symposion** [comment]
Looks to have been fixed by Roll20. Yay!
